// .agents/hooks/tests/tables/commit-message.js
// scripts/check-commit-msg.js's decisions: what the commit-msg hook blocks, what it warns about,
// and what it lets through. The issue-key rule reads the project's own tracker config, so each row
// names the files the repo it runs against holds.
const commitMsg = require("../../../../scripts/check-commit-msg");
const { withRoot, text } = require("../fixtures");

// A message's verdict: blocked with a problem containing `blocks`, or accepted, warned about
// `warns` or about nothing when `warns` is null. `summary` is a substring of what an accepted
// message prints.
function commitMessageDecisions(t) {
    const WHY = "The git-commit skill writes them; this holds whatever wrote them to the\nsame rule, agent or human.";
    const TRACKER = "docs/agents/issue-tracker.md";
    const rows = [
        // files, message, blocks, warns, summary, why
        [{}, text("feat(hooks): check the shape of every commit message", "", WHY), null, "PROJ-123", "conventional",
            "a conventional subject with a body passes"],
        [{}, text("Route aspnet-core for the engineer"), "not a conventional commit", undefined, null,
            "a sentence-style subject is rejected"],
        [{}, text("chore: tidy the lock file."), "ends with a full stop", undefined, null,
            "a subject ending in a full stop is rejected"],
        [{}, text("Merge branch master into feature"), null, null, "generated by git",
            "a merge message git wrote itself is not checked"],
        [{}, text("feat(hooks): warn when a commit cites no issue key", "", "The key is encouragement, not a gate: a change can be real before anyone\nhas raised a ticket for it."),
            null, "no issue key", "conventional", "a message citing no issue warns but is not rejected"],
        [{}, text("fix(hooks): cite the ticket this change came from (AB-42)", "", "The key ties the commit back to the work item that asked for it."),
            null, null, "conventional", "a message citing an issue passes without the warning"],
        [{}, text("fix: fixing bugs", "", "A body long enough to pass the body rule on its own."), "the description is 2 word(s)", undefined, null,
            "a two-word description is rejected however long the body"],
        [{}, text("feat(hooks): reject a commit that carries no body at all"), "there is no description", undefined, null,
            "a subject with no body is rejected"],
        [{}, text("feat(hooks): reject a body that is only a trailer line", "", "Refs: AB-42"), "there is no description", undefined, null,
            "a body that is only a trailer does not count as a description"],
        [{}, text("feat(hooks): count an issue key only where it refers", "", 'A body that merely quotes "Refs: AB-42" as an example of a trailer is\nprose about a ticket, not a reference to one.'),
            null, "no issue key", "conventional", "a key quoted in the body is prose, not a reference, so the warning stands"],
        [{}, text("feat(hooks): accept an issue key from a trailer line", "", "The trailer is where Git convention puts a reference.", "", "Refs: AB-42"),
            null, null, "conventional", "a key in a trailer line counts, so no warning"],

        // What an issue reference looks like is the project's decision, read from its own tracker
        // config and MEMORY.md. Each of these is a valid message, so only the warning varies.
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "AB-123", "conventional", "the project's own key becomes the example in the warning"],
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month.", "", "Refs: AB-42"),
            null, null, "conventional", "a key matching the project's own is a reference"],
        // GitHub Issues cite #42, which is nothing like AB-42, so a project says so with a regular
        // expression and is warned about the right thing.
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "#\\d+", "conventional", "a configured key format replaces the example"],
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run (#42)", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a reference matching the configured format counts"],
        // Smart commits read the key bare and a # word after it as a command, one per line, so a hashed
        // key never links and a command belongs on a trailer, not in the subject.
        [{}, text("fix(hooks): cite the ticket this change came from (#AB-42)", "", "The key ties the commit back to the work item that asked for it."),
            null, '"AB-42" not "#AB-42"', "conventional", "a hashed key warns, since smart commits read # as a command"],
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month.", "", "Refs: #AB-42"),
            null, '"AB-42" not "#AB-42"', "conventional", "a hashed key in a trailer warns too"],
        [{}, text("fix(hooks): cite the ticket AB-42 #time 1h", "", "The key ties the commit back to the work item that asked for it."),
            null, '"Refs: AB-42 #time"', "conventional", "a smart-commit command in the subject warns"],
        [{}, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month.", "", "Refs: AB-42 #time 1h 30m", "Refs: AB-42 #comment ready for review", "Refs: AB-42 #start-progress"),
            null, null, "conventional", "smart-commit commands on trailer lines after a bare key pass"],
        [{}, text("fix(lexer): keep #include lines out of the token stream", "", "The lexer read the directive as an identifier."),
            null, "no issue key", "conventional", "a # word in a subject with no key is prose, not a command"],
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run (#42)", "", "Invoices were cut by hand every month.", "", "Refs: #AB-42"),
            null, null, "conventional", "a configured format owns the hash, so nothing reads as a hashed key"],
        // A project that plans in docs/ has already answered the question, so asking again on every
        // commit is asking for something it said it does not have.
        [{ "MEMORY.md": "- **Issue tracker:** none\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a project recording no tracker is never warned"],
    ];
    for (const [files, message, blocks, warns, summary, why] of rows) {
        const r = withRoot(files, root => commitMsg.check(message, root));
        const detail = JSON.stringify(r);
        const verdict = blocks
            ? r.problems.some(p => p.includes(blocks))
            : !r.problems.length && r.summary.includes(summary)
                && (warns === null ? !r.warnings.length : r.warnings.length === 1 && r.warnings[0].includes(warns))
                && !(warns === "#\\d+" && r.warnings[0].includes("PROJ-123"));
        t.ok(verdict, `check-commit-msg: ${why}`, detail);
    }
}

// A coding agent appends "Co-authored-by: <itself>" because its own system prompt tells it to, so
// asking it to stop is a rule it forgets and a rejection it cannot satisfy. The hook drops the line
// instead. A human pair is credited exactly as Git intends: the discriminator is the address no
// person reads, not the name, because Claude is also a name parents give children.
function agentTrailersAreDropped(t) {
    const BODY = "A body long enough to satisfy the description rule.";
    const CLAUDE = "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>";
    const COPILOT = "Co-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>";
    const HUMAN = "Co-authored-by: Jane Roe <jane@example.com>";
    const subject = "feat(hooks): drop the co-author trailer an agent writes";
    const rows = [
        // message, what the trailer block should be afterwards, who was dropped, why
        [text(subject, "", BODY, "", CLAUDE), "", "Claude Opus 5", "an agent's trailer is dropped, and it is named"],
        [text(subject, "", BODY, "", COPILOT), "", "Copilot", "a bot account at a noreply address is an agent"],
        [text(subject, "", BODY, "", HUMAN), HUMAN, null, "a person keeps the credit Git's convention is for"],
        [text(subject, "", BODY, "", "Co-authored-by: Claude Dupont <claude.dupont@example.fr>"),
            "Co-authored-by: Claude Dupont <claude.dupont@example.fr>", null,
            "a person named Claude at their own address is not an agent"],
        [text(subject, "", BODY, "", HUMAN, CLAUDE), HUMAN, "Claude Opus 5", "the human stays where the agent goes"],
        [text(subject, "", BODY, "", "Refs: AB-42", CLAUDE), "Refs: AB-42", "Claude Opus 5", "other trailers are left alone"],
        [text(subject, "", BODY), "", null, "a message with no trailer is not rewritten"],
    ];
    for (const [message, kept, who, why] of rows) {
        const r = commitMsg.strip(message);
        const tail = r.message.split("\n").filter(l => /^[A-Za-z][A-Za-z-]*:\s/.test(l)).join("\n");
        const named = who === null ? !r.dropped.length : r.dropped.length === 1 && r.dropped[0].includes(who);
        t.ok(tail === kept && named, `check-commit-msg: ${why}`, JSON.stringify(r));
    }
    // What is left has to still be a commit message: no trailing blank where the trailer was, and
    // the body still ends in one newline, the way Git wrote it.
    const stripped = commitMsg.strip(text(subject, "", BODY, "", CLAUDE)).message;
    t.ok(stripped === text(subject, "", BODY), "check-commit-msg: dropping the last trailer leaves no blank line behind", JSON.stringify(stripped));
}

module.exports = [
    commitMessageDecisions,
    agentTrailersAreDropped,
];
