// .agents/hooks/tests/tables/commit-message.js
// scripts/check-commit-msg.js's decisions: what the commit-msg hook blocks, what it warns about,
// and what it lets through. The issue-key rule reads the project's own tracker config, so each row
// names the files the repo it runs against holds.
const commitMsg = require("../../../../scripts/check-commit-msg");
const { withRoot, text } = require("../fixtures");

// A message's verdict: blocked with a problem containing `blocks`, or accepted, warned about
// `warns` or about nothing when `warns` is null. `summary` is a substring of what an accepted
// message prints.
function commitMessageDecisions(t) {
    const WHY = "The git-commit skill writes them; this holds whatever wrote them to the\nsame rule, agent or human.";
    const TRACKER = "docs/agents/issue-tracker.md";
    const rows = [
        // files, message, blocks, warns, summary, why
        [{}, text("feat(hooks): check the shape of every commit message", "", WHY), null, "PROJ-123", "conventional",
            "a conventional subject with a body passes"],
        [{}, text("Route aspnet-core for the engineer"), "not a conventional commit", undefined, null,
            "a sentence-style subject is rejected"],
        [{}, text("chore: tidy the lock file."), "ends with a full stop", undefined, null,
            "a subject ending in a full stop is rejected"],
        [{}, text("Merge branch master into feature"), null, null, "generated by git",
            "a merge message git wrote itself is not checked"],
        [{}, text("feat(hooks): warn when a commit cites no issue key", "", "The key is encouragement, not a gate: a change can be real before anyone\nhas raised a ticket for it."),
            null, "no issue key", "conventional", "a message citing no issue warns but is not rejected"],
        [{}, text("fix(hooks): cite the ticket this change came from (AB-42)", "", "The key ties the commit back to the work item that asked for it."),
            null, null, "conventional", "a message citing an issue passes without the warning"],
        [{}, text("fix: fixing bugs", "", "A body long enough to pass the body rule on its own."), "the description is 2 word(s)", undefined, null,
            "a two-word description is rejected however long the body"],
        [{}, text("feat(hooks): reject a commit that carries no body at all"), "there is no description", undefined, null,
            "a subject with no body is rejected"],
        [{}, text("feat(hooks): reject a body that is only a trailer line", "", "Refs: AB-42"), "there is no description", undefined, null,
            "a body that is only a trailer does not count as a description"],
        [{}, text("feat(hooks): count an issue key only where it refers", "", 'A body that merely quotes "Refs: AB-42" as an example of a trailer is\nprose about a ticket, not a reference to one.'),
            null, "no issue key", "conventional", "a key quoted in the body is prose, not a reference, so the warning stands"],
        [{}, text("feat(hooks): accept an issue key from a trailer line", "", "The trailer is where Git convention puts a reference.", "", "Refs: AB-42"),
            null, null, "conventional", "a key in a trailer line counts, so no warning"],

        // What an issue reference looks like is the project's decision, read from its own tracker
        // config and MEMORY.md. Each of these is a valid message, so only the warning varies.
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "AB-123", "conventional", "the project's own key becomes the example in the warning"],
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month.", "", "Refs: AB-42"),
            null, null, "conventional", "a key matching the project's own is a reference"],
        // GitHub Issues cite #42, which is nothing like AB-42, so a project says so with a regular
        // expression and is warned about the right thing.
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "#\\d+", "conventional", "a configured key format replaces the example"],
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run (#42)", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a reference matching the configured format counts"],
        // A project that plans in docs/ has already answered the question, so asking again on every
        // commit is asking for something it said it does not have.
        [{ "MEMORY.md": "- **Issue tracker:** none\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a project recording no tracker is never warned"],
    ];
    for (const [files, message, blocks, warns, summary, why] of rows) {
        const r = withRoot(files, root => commitMsg.check(message, root));
        const detail = JSON.stringify(r);
        const verdict = blocks
            ? r.problems.some(p => p.includes(blocks))
            : !r.problems.length && r.summary.includes(summary)
                && (warns === null ? !r.warnings.length : r.warnings.length === 1 && r.warnings[0].includes(warns))
                && !(warns === "#\\d+" && r.warnings[0].includes("PROJ-123"));
        t.ok(verdict, `check-commit-msg: ${why}`, detail);
    }
}

module.exports = [
    commitMessageDecisions,
];
