// .agents/hooks/tests/tables.js
// Decision tables: a check's input and the verdict it must give, run in this process against a
// throwaway root. A command reads the repo it sits in, so a fixture piped to one can only ever see
// this checkout's MEMORY.md and tracker config, and a case about another project's settings had no
// way in. check(input, root) takes the repo as an argument, so each row names the files that repo
// holds and nothing here depends on the checkout the suite runs in.
// Registered like self-checks.js: test.js runs the exported array after it, and a function left out
// of the array is caught by everyCheckIsRegistered there. cases.tsv keeps one row per script, which
// proves the command line still reaches the decision.
const fs = require("fs");
const os = require("os");
const path = require("path");
const commitMsg = require("../../../scripts/check-commit-msg");
const todo = require("../../../scripts/check-todo");
const docsCheck = require("../../../scripts/docs-check");
const stagedDocs = require("../../../scripts/check-staged-docs");
const facts = require("../../../scripts/project-facts");
const skills = require("../../../scripts/skills");
const repoView = require("../../../scripts/repo-view");
const scriptsLib = require("../../../scripts/lib");
const checkHarness = require("../../../scripts/check-harness");
const { spawnSync } = require("child_process");

// A temp repo holding `files` (repo-relative path -> content), handed to `use`, and removed after.
function withRoot(files, use) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "harness-table-"));
    try {
        for (const [rel, text] of Object.entries(files)) {
            fs.mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true });
            fs.writeFileSync(path.join(dir, rel), text);
        }
        return use(dir);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

const text = (...lines) => lines.join("\n") + "\n";

// A message's verdict: blocked with a problem containing `blocks`, or accepted, warned about
// `warns` or about nothing when `warns` is null. `summary` is a substring of what an accepted
// message prints.
function commitMessageDecisions(t) {
    const WHY = "The git-commit skill writes them; this holds whatever wrote them to the\nsame rule, agent or human.";
    const TRACKER = "docs/agents/issue-tracker.md";
    const rows = [
        // files, message, blocks, warns, summary, why
        [{}, text("feat(hooks): check the shape of every commit message", "", WHY), null, "PROJ-123", "conventional",
            "a conventional subject with a body passes"],
        [{}, text("Route aspnet-core for the engineer"), "not a conventional commit", undefined, null,
            "a sentence-style subject is rejected"],
        [{}, text("chore: tidy the lock file."), "ends with a full stop", undefined, null,
            "a subject ending in a full stop is rejected"],
        [{}, text("Merge branch master into feature"), null, null, "generated by git",
            "a merge message git wrote itself is not checked"],
        [{}, text("feat(hooks): warn when a commit cites no issue key", "", "The key is encouragement, not a gate: a change can be real before anyone\nhas raised a ticket for it."),
            null, "no issue key", "conventional", "a message citing no issue warns but is not rejected"],
        [{}, text("fix(hooks): cite the ticket this change came from (AB-42)", "", "The key ties the commit back to the work item that asked for it."),
            null, null, "conventional", "a message citing an issue passes without the warning"],
        [{}, text("fix: fixing bugs", "", "A body long enough to pass the body rule on its own."), "the description is 2 word(s)", undefined, null,
            "a two-word description is rejected however long the body"],
        [{}, text("feat(hooks): reject a commit that carries no body at all"), "there is no description", undefined, null,
            "a subject with no body is rejected"],
        [{}, text("feat(hooks): reject a body that is only a trailer line", "", "Refs: AB-42"), "there is no description", undefined, null,
            "a body that is only a trailer does not count as a description"],
        [{}, text("feat(hooks): count an issue key only where it refers", "", 'A body that merely quotes "Refs: AB-42" as an example of a trailer is\nprose about a ticket, not a reference to one.'),
            null, "no issue key", "conventional", "a key quoted in the body is prose, not a reference, so the warning stands"],
        [{}, text("feat(hooks): accept an issue key from a trailer line", "", "The trailer is where Git convention puts a reference.", "", "Refs: AB-42"),
            null, null, "conventional", "a key in a trailer line counts, so no warning"],

        // What an issue reference looks like is the project's decision, read from its own tracker
        // config and MEMORY.md. Each of these is a valid message, so only the warning varies.
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "AB-123", "conventional", "the project's own key becomes the example in the warning"],
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month.", "", "Refs: AB-42"),
            null, null, "conventional", "a key matching the project's own is a reference"],
        // GitHub Issues cite #42, which is nothing like AB-42, so a project says so with a regular
        // expression and is warned about the right thing.
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "#\\d+", "conventional", "a configured key format replaces the example"],
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run (#42)", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a reference matching the configured format counts"],
        // A project that plans in docs/ has already answered the question, so asking again on every
        // commit is asking for something it said it does not have.
        [{ "MEMORY.md": "- **Issue tracker:** none\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a project recording no tracker is never warned"],
    ];
    for (const [files, message, blocks, warns, summary, why] of rows) {
        const r = withRoot(files, root => commitMsg.check(message, root));
        const detail = JSON.stringify(r);
        const verdict = blocks
            ? r.problems.some(p => p.includes(blocks))
            : !r.problems.length && r.summary.includes(summary)
                && (warns === null ? !r.warnings.length : r.warnings.length === 1 && r.warnings[0].includes(warns))
                && !(warns === "#\\d+" && r.warnings[0].includes("PROJ-123"));
        t.ok(verdict, `check-commit-msg: ${why}`, detail);
    }
}

// A ledger's verdict: blocked with a problem containing `blocks`, or accepted with a summary
// containing `summary`. Sources that look like paths resolve against the root each row is given.
function todoDecisions(t) {
    const REPO = { "AGENTS.md": "# Agents\n", "scripts/githooks-init.js": "// init\n", "src/billing.cs": "// there\n" };
    const rows = [
        // ledger, blocks, summary, why
        [text("# TODO", "", "What has nowhere else to live. The loose-ends skill has the format.", "",
            "- [ ] Does the initialisation gate belong on push as well? #question (AGENTS.md)",
            "- [ ] Every clone has run githooks-init #assumption @yaroslav (scripts/githooks-init.js:1)",
            "- [ ] No test covers the relink path #deferred (jira:AB-42)",
            "  - [ ] and the absolute-link case under it is untested too",
            "- [ ] Revisit once the spec settles #deferred (https://example.com/spec)"),
            null, "all well formed", "every tag, a subtask, an assignee and each kind of source all pass"],
        [text("- [ ] An entry with no file header #question (AGENTS.md)"), 'must open with "# TODO"', null,
            "todo-md requires the header, so a file of bare entries is rejected"],
        [text("# TODO", "", "- [ ] Something vague #todo (AGENTS.md)"), "unknown tag", null, "a tag outside the three kinds is rejected"],
        [text("# TODO", "", "- [x] This one was answered #question (AGENTS.md)"), 'a "[x]" entry', null, "a resolved entry is deleted, not ticked"],
        [text("# TODO", "", "- [-] We decided against this #deferred (AGENTS.md)"), 'a "[-]" entry', null,
            "a declined entry is deleted too, though todo-md would keep it"],
        [text("# TODO", "", "- [ ] Where should this live? #question"), "no source", null,
            "an entry that says nothing about where it came from is rejected"],
        [text("# TODO", "", "- [ ] Where should this live? #question (during the review)"), "is not a source", null,
            "prose in place of a source is rejected"],
        [text("# TODO", "", "Nothing outstanding right now."), null, "0 open item(s)", "a file with the header and no entries passes"],
        ["", null, "nothing to check", "an empty ledger is not a problem"],
        [text("# TODO", "", "- [ ] Confirm the rounding rule #question (src/billing.cs:12)"), null, "1 open item(s)",
            "a path:line source resolves in the root it was given"],
        // As a command, the root is always this checkout, so a fixture could only cite a file the
        // template happens to ship; this is the row that proves the resolution rather than assuming it.
        [text("# TODO", "", "- [ ] Confirm the rounding rule #question (scripts/lib.js)"), "is not a source", null,
            "a path outside that root is not a source, however real it is here"],
        [text("# TODO", "", "- [ ] Split the billing folder #deferred (src)"), "is not a source", null,
            "a bare folder name is prose, as it is in a Derived from line"],
        [text("# TODO", "", "- [ ] Split the billing folder #deferred (src/)"), null, "1 open item(s)",
            "a folder written with its slash is a source"],
        [text("# TODO", "", "- [ ] Chase the ticket #deferred (jira:ab-42)"), "is not a source", null,
            "a lower-case Jira key is rejected, as docs-check rejects it"],
    ];
    for (const [ledger, blocks, summary, why] of rows) {
        const r = withRoot(REPO, root => todo.check(ledger, root));
        const verdict = blocks ? r.problems.some(p => p.includes(blocks)) : !r.problems.length && r.summary.includes(summary);
        t.ok(verdict, `check-todo: ${why}`, r.problems.join("\n") || r.summary);
    }
}

// What counts as a source, the one rule "Derived from:", MEMORY.md's Requirements and TODO.md share.
function sourceDecisions(t) {
    const REPO = { "INTENT.md": "# INTENT.md\n", "src/billing.cs": "// there\n", "docs/brief.md": "# Brief\n" };
    const rows = [
        // token, is a source, why
        ["https://example.com/spec", true, "a URL"],
        ["jira:AB-42", true, "an upper-case Jira key"],
        ["jira:MY_PROJ-7", true, "a Jira key with an underscore, which Jira allows"],
        ["jira:ab-42", false, "a lower-case Jira key, which Jira never issues"],
        ["src/billing.cs", true, "a path that exists"],
        ["src/billing.cs:12", true, "path:line, where the file exists"],
        ["src/billing.cs:12-40", true, "path:from-to, where the file exists"],
        ["src/missing.cs:12", false, "path:line whose file does not exist"],
        ["src/", true, "a folder, written with its slash"],
        ["src", false, "a bare word, even one naming a real folder"],
        ["INTENT.md", true, "a file at the root"],
        ["Node.js", false, "prose with a dot"],
        ["during the review", false, "prose"],
    ];
    withRoot(REPO, root => {
        for (const [token, want, why] of rows) {
            t.ok(docsCheck.isSource(token, root) === want, `isSource: ${why}`, `${token} -> ${!want}`);
        }
    });
}

// Which files are the chain. The edit hook and the pre-commit hook both ask inChain, so one table
// pins what an edit and a commit check.
function chainMembership(t) {
    const rows = [
        ["docs/brd/0001-x.md", true, "a document under docs/"],
        ["docs/README.md", true, "any Markdown under docs/"],
        ["AGENTS.md", true, "the table that defines the stages"],
        ["MEMORY.md", true, "MEMORY.md, whose Requirements line enters the chain"],
        ["INTENT.md", true, "INTENT.md"],
        ["docs/diagram.png", false, "a file under docs/ that is not Markdown"],
        ["README.md", false, "Markdown outside docs/"],
        ["src/docs/x.md", false, "a docs/ folder that is not at the root"],
    ];
    for (const [file, want, why] of rows) {
        t.ok(docsCheck.inChain(file) === want, `inChain: ${why}`, `${file} -> ${!want}`);
    }
    const staged = rows.map(r => r[0]);
    t.ok(JSON.stringify(stagedDocs.chainFiles(staged)) === JSON.stringify(staged.filter(docsCheck.inChain)),
        "the pre-commit hook's staged filter is inChain", stagedDocs.chainFiles(staged).join(" "));
}

// What every reader of project facts sees, from the texts of MEMORY.md and INTENT.md (null: no such
// file). A label reads null when nothing gives it, "" when it is unanswered, and its value otherwise.
function projectFactDecisions(t) {
    const INTENT = text("# INTENT.md", "", "## Product", "", "**Acme Billing** invoices small firms monthly.", "", "## MVP stories", "");
    const rows = [
        // memory, intent, label, expected, why
        [text("- **Language:** C#"), null, "Language", "C#", "a dash bullet with the colon inside the bold"],
        [text("* **Language**: C#"), null, "Language", "C#", "a star bullet with the colon after the bold"],
        [text("-**Language:** C#"), null, "Language", "C#", "no space after the bullet"],
        [text("- **language:** C#"), null, "Language", "C#", "the label in another case"],
        [text("- **Language:**   C#  "), null, "Language", "C#", "the value is trimmed"],
        ["- **Language:** C#\r\n- **Unit type:** service\r\n", null, "Unit type", "service", "CRLF line endings"],
        [text("Language: C#"), null, "Language", null, "an unbolded line is prose, not a fact"],
        [text("- Language: C#"), null, "Language", null, "an unbolded bullet is prose too"],
        [text("**Language:** C#"), null, "Language", null, "a bold label with no bullet is not a fact line"],
        [text("- **Languages:** C#"), null, "Language", null, "a longer label is another fact"],
        [text("- **Runtime / package manager:** Node 22 / pnpm"), null, "Runtime / package manager", "Node 22 / pnpm",
            "a label holding a slash"],
        [null, null, "Language", null, "no MEMORY.md at all"],
        [text("- **Language:**"), null, "Language", "", "an empty value is unanswered"],
        [text("- **Language:** <language>"), null, "Language", "", "a placeholder is unanswered"],
        [text("- **Language:** <language> <version>"), null, "Language", "", "several placeholders and nothing else are unanswered"],
        [text("- **Issue tracker:** <tracker> at <url>"), null, "Issue tracker", "<tracker> at <url>",
            "words beside placeholders make an answer, kept whole"],
        [text("- **Issue tracker:** none"), null, "Issue tracker", "none", "an optional fact reads like any other"],
        // INTENT.md owns the name and purpose outright; the configuration stays MEMORY.md's.
        [text("- **Name:** Old Name"), INTENT, "Name", "Acme Billing", "INTENT.md's bold name wins over MEMORY.md"],
        [text("- **Purpose:** old"), INTENT, "Purpose", "invoices small firms monthly.", "the purpose is INTENT.md's prose"],
        [text("- **Name:** Old Name"), INTENT.replace("**Acme Billing** ", ""), "Name", "",
            "an INTENT.md naming no product leaves Name unanswered, with no fallback"],
        [text("- **Name:** Old Name"), text("# INTENT.md", "", "## MVP stories"), "Name", null,
            "an INTENT.md with no Product gives no name, with no fallback"],
        [null, text("# INTENT.md", "", "## Product", "", "**<name>** <purpose>"), "Name", "", "a template INTENT.md is unanswered"],
        [text("- **Language:** C#"), INTENT, "Language", "C#", "INTENT.md does not stand in for configuration"],
        [text("- **Name:** Acme"), null, "Name", "Acme", "without INTENT.md the name is MEMORY.md's"],
    ];
    for (const [memory, intent, label, want, why] of rows) {
        const got = facts.readFacts({ memory, intent })[label];
        t.ok(got === want, `project facts: ${why}`, `${label} -> ${JSON.stringify(got)}, wanted ${JSON.stringify(want)}`);
    }

    const all = text(...facts.FACTS.map(f => `- **${f.label}:** x`));
    t.ok(facts.unanswered(facts.readFacts({ memory: all })).length === 0, "project facts: nothing unanswered when every line has a value");
    t.ok(facts.unanswered(facts.readFacts({ memory: text("- **Issue tracker:** Jira") })).join() === facts.FACTS.filter(f => f.required).map(f => f.label).join(),
        "project facts: unanswered lists the required facts only, in order", facts.unanswered(facts.readFacts({})).join());

    const parsed = facts.readIntent(INTENT);
    t.ok(parsed.title && parsed.stories && parsed.product.name === "Acme Billing" && parsed.product.purpose === "invoices small firms monthly.",
        "project facts: readIntent separates the bold name from the purpose", JSON.stringify(parsed));

    // readFactsAt reads the files a root holds.
    withRoot({ "MEMORY.md": text("- **Language:** C#") }, root => {
        t.ok(facts.readFactsAt(root).Language === "C#", "project facts: readFactsAt reads MEMORY.md at the root");
    });
}

// The skill roster of a repo built for it: what the lock records against what the disk holds, who
// routes each skill and through which file, and whether the licence notice is current. The
// upstream's own roster only ever shows the healthy case, so every odd shape lives here.
function skillRosterDecisions(t) {
    const skill = (name, extra = "") => text("---", `name: ${name}`, "description: Does one thing.", ...(extra ? [extra] : []), "---", "Body");
    const lock = names => JSON.stringify({ version: 1, skills: Object.fromEntries(Object.entries(names).map(([n, source]) => [n, { source }])) });
    const ACME = "acme/skills\tMIT\tCopyright (c) Acme\thttps://example.com/LICENSE\t-\n";
    const files = {
        ".agents/skills/local-one/SKILL.md": skill("local-one", "disable-model-invocation: true"),
        ".agents/skills/vendored-one/SKILL.md": skill("vendored-one"),
        ".agents/skills/vendored-two/SKILL.md": skill("vendored-two"),
        ".agents/skills/no-skill-md/notes.md": "not a skill\n",
        ".agents/skills/stray.txt": "a file, not a folder\n",
        "skills-lock.json": lock({ "vendored-one": "acme/skills", "vendored-two": "other/skills", "gone-one": "acme/skills" }),
        "scripts/skill-licences.tsv": text("# comment", ACME.trim()),
        ".agents/routing.md": text("# Routing", "", "Preamble naming `local-one`.", "", "## Shared rows", "", "Read by `alpha`.", "", "| `vendored-one` | ... |"),
        ".agents/agents/alpha.md": text("---", "name: alpha", "---", "Route through `local-one`, then routing.md, \"Shared rows\"."),
        ".agents/agents/beta.md": text("---", "name: beta", "---", "Mentions \"Shared rows\" but never the routing file."),
        ".agents/agents/not-an-agent.md": text("Names `vendored-two` with no frontmatter."),
        "AGENTS.md": text("Every session may run `vendored-two`."),
    };
    withRoot(files, root => {
        const r = skills.readRoster(root);
        const entry = name => r.entries.find(e => e.name === name) || {};
        const s = name => r.skills.find(x => x.name === name) || {};
        t.ok(r.entries.map(e => e.name).join() === "local-one,no-skill-md,stray.txt,vendored-one,vendored-two",
            "skill roster: every entry under .agents/skills is listed, sorted", r.entries.map(e => e.name).join());
        t.ok(entry("no-skill-md").dir && !entry("no-skill-md").hasSkillMd && entry("no-skill-md").frontmatter === null,
            "skill roster: a folder with no SKILL.md is an entry marked as such, and not a skill");
        t.ok(!entry("stray.txt").dir && !entry("stray.txt").hasSkillMd, "skill roster: a stray file is an entry marked not a folder");
        t.ok(r.skills.map(x => x.name).join() === "local-one,vendored-one,vendored-two", "skill roster: skills are the entries holding a SKILL.md",
            r.skills.map(x => x.name).join());
        t.ok(r.missing.join() === "gone-one", "skill roster: a skill the lock records and the disk lacks is missing", r.missing.join());
        t.ok(s("local-one").source === "local" && !s("local-one").vendored && s("vendored-one").source === "acme/skills" && s("vendored-one").vendored,
            "skill roster: the source is the lock's, or local when the lock does not record the skill");
        t.ok(s("local-one").invoke === "`/local-one`" && s("vendored-one").invoke === "by description",
            "skill roster: disable-model-invocation makes a skill invoked by name");
        t.ok(s("local-one").agents.join() === "alpha", "skill roster: an agent routes a skill its own body names", s("local-one").agents.join());
        t.ok(s("vendored-one").agents.join() === "alpha",
            "skill roster: a routing.md section credits its skills to the agents naming the file and the section, and no other",
            s("vendored-one").agents.join());
        t.ok(!r.routing.agents["not-an-agent"], "skill roster: a file with no frontmatter name is not an agent");
        t.ok(s("vendored-two").everywhere && !s("vendored-two").agents.length && !s("vendored-one").everywhere,
            "skill roster: a skill AGENTS.md names is reached everywhere, apart from any agent");
        const [section] = r.routing.sections;
        t.ok(r.routing.sections.length === 1 && section.title === "Shared rows" && section.readBy.join() === "alpha" && !section.skills.has("local-one"),
            "skill roster: routing.md's sections exclude its preamble and carry their Read by line", JSON.stringify(r.routing.sections.map(x => x.title)));

        t.ok(r.notices.orphans.join() === "vendored-two (other/skills)" && !r.notices.current,
            "skill roster: a vendored skill no licence row covers is an orphan", r.notices.orphans.join());
        t.ok(!skills.writeNotices(root).written && !fs.existsSync(path.join(root, skills.NOTICES)),
            "skill roster: the notice is not written while there is an orphan");
        fs.appendFileSync(path.join(root, skills.LICENCES), "other/skills\tApache-2.0\t-\thttps://example.com/APACHE\tKeep the NOTICE file.\n");
        t.ok(skills.writeNotices(root).written && skills.readRoster(root).notices.current,
            "skill roster: once every upstream has a row the notice is written, and then current");
        const notice = fs.readFileSync(path.join(root, skills.NOTICES), "utf8");
        t.ok(/`vendored-one`/.test(notice) && /not stated upstream/.test(notice) && /Keep the NOTICE file/.test(notice) && /`local-one`/.test(notice),
            "skill roster: the notice lists each upstream's skills, a missing holder, the notes and the local skills", notice);
        t.ok(!skills.writeNotices(root).written, "skill roster: a current notice is not rewritten");

        let linked = true;
        try { fs.symlinkSync("local-one", path.join(root, ".agents/skills/alias"), "dir"); } catch { linked = false; }
        if (!linked) t.skip("skill roster: this OS refuses symlinks, so the linked entry goes unchecked");
        else t.ok(skills.readRoster(root).entries.find(e => e.name === "alias").link, "skill roster: a link under .agents/skills is an entry marked as a link");
    });

    withRoot({}, root => {
        const r = skills.readRoster(root);
        t.ok(r.lock === null && !r.entries.length && !r.skills.length && !r.missing.length && !r.routing.sections.length,
            "skill roster: a repo with no harness files has an empty roster and no lock");
    });

    withRoot({ ".agents/skills/one/SKILL.md": skill("one"), ".cursor/skills/.keep": "" }, root => {
        let first;
        try { first = skills.relink(root); } catch (e) { t.skip(`skill roster: this OS refuses symlinks, so relink goes unchecked (${e.code})`); return; }
        const link = path.join(root, ".cursor/skills/one");
        t.ok(first.added === 1 && fs.readlinkSync(link).split(path.sep).join("/") === "../../.agents/skills/one",
            "skill roster: relink links an unlinked skill into a per-skill folder, relative", JSON.stringify(first));
        const again = skills.relink(root);
        t.ok(again.added === 0 && again.kept === 1, "skill roster: relink leaves a relative link alone", JSON.stringify(again));
    });
}

// A repo view answers the same four questions whichever adapter sits behind it. The map is what
// the docs-check self-checks run on, so its answers about folders are pinned here.
function repoViewDecisions(t) {
    const map = repoView.fromMap({ "docs/brd/0001-a.md": "A\n", "docs/brd/0002-b.md": "B\n", "docs/prd/0001-c.md": "C\n", "AGENTS.md": "x" });
    const rows = [
        [map.exists("docs"), true, "a folder is whatever a path implies"],
        [map.exists("docs/brd/"), true, "a folder written with its slash"],
        [map.isFile("docs/brd"), false, "a folder is not a file"],
        [map.exists("doc"), false, "a prefix of a name is not a folder"],
        [map.read("docs/brd/0001-a.md"), "A\n", "read gives the text as held"],
        [map.read("./AGENTS.md"), "x", "a path is normalised before it is looked up"],
        [map.read("docs/brd"), null, "read of a folder is null"],
        [map.read("MEMORY.md"), null, "read of an absent file is null"],
        [map.list("docs").join(), "brd,prd", "list gives the names directly inside, sorted"],
        [map.list("docs/adr").join(), "", "list of an absent folder is empty"],
    ];
    for (const [got, want, why] of rows) t.ok(got === want, `repo view: ${why}`, JSON.stringify(got));
    withRoot({ "a.md": "on disk\n", "sub/b.md": "b\n" }, dir => {
        const disk = repoView.worktree(dir);
        t.ok(disk.read("a.md") === "on disk\n" && disk.list(".").join() === "a.md,sub" && disk.isFile("sub") === false,
            "repo view: the working tree answers from the disk", disk.list(".").join());
        let threw = false;
        const missing = path.join(dir, "no-such-dir");
        try { repoView.index(missing); } catch { threw = true; }
        t.ok(threw && repoView.indexModes(missing) === null, "repo view: an index nobody can read throws rather than reading empty");
    });
}

// The pre-commit hook checks what the commit records. A real repo whose index and working tree
// disagree, each way round, with a source the documents cite only on disk.
function stagedChainDecisions(t) {
    const git = (dir, ...args) => spawnSync("git", args, { cwd: dir, encoding: "utf8" });
    const agents = fs.readFileSync(path.join(__dirname, "..", "..", "..", "AGENTS.md"), "utf8");
    const brd = text("# BRD-0001: Billing", "", "**Derived from:** .scratch/interview.md", "", "- BR-1: Bill monthly.");
    const skillFiles = Object.fromEntries(docsCheck.readChain(path.join(__dirname, "..", "..", ".."))
        .stages.flatMap(s => s.skills).map(s => [`.agents/skills/${s}/SKILL.md`, ""]));
    withRoot({ "AGENTS.md": agents, ...skillFiles, ".scratch/interview.md": "notes\n", "docs/brd/0001-billing.md": brd }, dir => {
        if (git(dir, "init", "-q").status !== 0) { t.skip("staged chain: git is not available"); return; }
        git(dir, "add", "AGENTS.md", "docs");
        const docFile = path.join(dir, "docs", "brd", "0001-billing.md");
        const check = () => stagedDocs.check(dir, ["docs/brd/0001-billing.md"]);

        const clean = check();
        t.ok(!clean.problems.length && !clean.warnings.length, "staged chain: a staged document citing a source on disk passes",
            clean.problems.concat(clean.warnings).join("\n"));

        // Broken on disk only: the commit records the good blob.
        fs.writeFileSync(docFile, brd.replace("**Derived from:** .scratch/interview.md", ""));
        t.ok(!check().problems.length, "staged chain: a break saved but not staged does not block", check().problems.join("\n"));
        t.ok(docsCheck.check(dir).problems.length > 0, "staged chain: the same break does fail the working-tree check");

        // Broken in the index, fixed on disk: the commit would record the break.
        git(dir, "add", "docs");
        fs.writeFileSync(docFile, brd);
        const staged = check().problems;
        t.ok(staged.some(p => p.startsWith("docs/brd/0001-billing.md: missing a")),
            "staged chain: a break staged and fixed on disk blocks, naming the repo-relative path", staged.join("\n") || "(none)");

        // A document in the index and gone from the disk is still what the commit records.
        git(dir, "add", "docs");
        fs.writeFileSync(path.join(dir, "docs", "brd", "0002-late.md"), text("# BRD-0002: Late"));
        const view = repoView.staged(dir, docsCheck.CHAIN_PATHS);
        fs.rmSync(docFile);
        t.ok(view.isFile("docs/brd/0001-billing.md") && !view.exists("docs/brd/0002-late.md") && view.isFile(".scratch/interview.md"),
            "staged view: the chain from the index, an untracked document unseen, a source from the disk",
            view.list("docs/brd").join());
        t.ok(view.read("MEMORY.md") === null, "staged view: a chain file neither staged nor on disk reads null");

        const modes = repoView.indexModes(dir, ["AGENTS.md"]);
        t.ok(modes && modes.length === 1 && modes[0].file === "AGENTS.md" && !modes[0].link && !modes[0].exec && /^[0-9a-f]{40,64}$/.test(modes[0].object),
            "indexModes: a plain file, with its blob", JSON.stringify(modes));
    });
    withRoot({ "docs/brd/0001-x.md": "x\n" }, dir => {
        const r = stagedDocs.check(path.join(dir, "not-a-repo"), ["docs/brd/0001-x.md"]);
        t.ok(!r.problems.length && r.warnings.some(w => w.includes("could not read the staged documentation chain")),
            "staged chain: an unreadable index warns and lets the commit through", r.warnings.join("\n") || "(no warning)");
    });
}

// Which repo an entry point is about. Six places used to answer that differently -- a script read
// --root and ignored the variables, a hook read the variables and ignored --root -- so a check run
// one way saw a different repo from the same check run the other. One resolver answers now, and
// this is its precedence: the flag, then the first project-dir variable that is set, then the
// checkout the file lives in. root() reads argv and the environment, so each row is a real child
// process; the probe sits in a throwaway directory and requires the checkout's copy of the library.
function rootDecisions(t) {
    const LIB = path.resolve(__dirname, "../../../scripts/lib");
    const probe = `const lib = require(${JSON.stringify(LIB)});\n`
        + "process.stdout.write(JSON.stringify({ root: lib.root(), args: lib.args() }));\n";
    const real = p => { try { return fs.realpathSync(p); } catch { return p; } };
    const CHECKOUT = real(scriptsLib.CHECKOUT);
    const flag = dir => `${scriptsLib.ROOT_FLAG}${dir}`;
    withRoot({ "probe.js": probe, "not-a-dir.txt": "x\n" }, dir => {
        const elsewhere = real(os.tmpdir());
        const run = (args, vars) => {
            const env = { ...process.env };
            for (const v of scriptsLib.ROOT_ENV_VARS) delete env[v];
            const r = spawnSync(process.execPath, [path.join(dir, "probe.js"), ...args],
                { encoding: "utf8", env: { ...env, ...vars } });
            return { ...JSON.parse(r.stdout), warning: (r.stderr || "").trim() };
        };
        const rows = [
            // args, environment, the root it must return, the warning it must carry, why
            [[], {}, CHECKOUT, null, "nothing said: the checkout the file lives in"],
            [[flag(dir)], {}, dir, null, "the flag is the explicit answer"],
            [[flag(dir)], { CLAUDE_PROJECT_DIR: elsewhere }, dir, null, "the flag beats the harness's variable"],
            [[], { CLAUDE_PROJECT_DIR: dir }, dir, "is not the checkout this file lives in",
                "a hook follows the harness's variable, and says it is another checkout"],
            [[], { CURSOR_PROJECT_DIR: dir }, dir, "is not the checkout this file lives in", "every harness's variable, not just Claude's"],
            [[], { GEMINI_PROJECT_DIR: dir }, dir, "is not the checkout this file lives in", "Gemini's too"],
            [[], { CURSOR_PROJECT_DIR: elsewhere, CLAUDE_PROJECT_DIR: dir }, dir, "CLAUDE_PROJECT_DIR", "the first variable in the list wins"],
            [[], { CLAUDE_PROJECT_DIR: path.join(dir, "not-a-dir.txt") }, CHECKOUT, "is not a directory",
                "a variable naming no directory is ignored, and said so"],
            [[], { CLAUDE_PROJECT_DIR: path.join(dir, "gone") }, CHECKOUT, "is not a directory", "so is one naming nothing at all"],
        ];
        for (const [args, vars, want, warns, why] of rows) {
            const r = run(args, vars);
            t.ok(r.root === want && (warns === null ? !r.warning : r.warning.includes(warns)),
                `root: ${why}`, `${r.root}\n${r.warning || "(no warning)"}`);
        }
        const r = run([flag(dir), "--dry-run", "install"], {});
        t.ok(r.args.join(" ") === "--dry-run install", "root: args() hands on the command line without the flag", r.args.join(" "));
    });
}

// .claude/settings.json wires the three hooks, and nothing read it back after an update merged it.
// Each row is a settings file and the failure claudeHookLaunchersAreWired must report about it, run
// through check() against a root holding nothing else, so every other invariant stands down.
function hookLauncherDecisions(t) {
    const entry = (script, matcher) => ({
        ...(matcher ? { matcher } : {}),
        hooks: [{ type: "command", command: checkHarness.launcher(script), timeout: 20 }],
    });
    const wired = () => ({
        hooks: Object.fromEntries(checkHarness.CLAUDE_HOOKS.map(h => [h.event, [entry(h.script, h.matcher)]])),
    });
    const mine = { type: "command", command: "npm run lint" };
    const rows = [
        // the settings file, the failure it must produce (null: none), why
        [wired(), null, "the launcher table's own wiring passes"],
        [{ hooks: { ...wired().hooks, PreToolUse: [{ matcher: "Bash", hooks: [mine] }, ...wired().hooks.PreToolUse] } },
            null, "a hook the project added beside ours is not ours to judge"],
        [{ ...wired(), permissions: { allow: ["Bash(git status)"] } }, null, "a setting that is not a hook is left alone"],
        [{ hooks: { ...wired().hooks, SessionStart: undefined } }, "launches session-start.js on SessionStart, once",
            "an event whose entry a merge dropped"],
        [{ hooks: { ...wired().hooks, PostToolUse: [...wired().hooks.PostToolUse, ...wired().hooks.PostToolUse] } },
            "launches check-edit.js on PostToolUse, once", "the same script wired twice"],
        [{ hooks: { ...wired().hooks, PreToolUse: [entry("guard-command.js", "Bash|Edit")] } },
            "matches Bash", "a matcher that widened"],
        [{ hooks: { ...wired().hooks, SessionStart: [entry("session-start.js", "Bash")] } },
            "matches every tool", "a matcher on the entry that must have none"],
        [{ hooks: { ...wired().hooks, PreToolUse: [{ matcher: "Bash", hooks: [{ type: "command", command: 'node "$CLAUDE_PROJECT_DIR/.agents/hooks/guard-command.js"' }] }] }},
            "is the launcher every shell runs", "a command built on a variable only Claude Code sets"],
    ];
    for (const [settings, wants, why] of rows) {
        withRoot({ ".claude/settings.json": JSON.stringify(settings, null, 2) }, dir => {
            const said = checkHarness.check(dir).failed.map(f => `${f.title}\n${f.detail}`).join("\n");
            t.ok(wants === null ? !said : said.includes(wants), `hook launcher: ${why}`, said || "(nothing reported)");
        });
    }
    withRoot({ ".claude/settings.json": "{ not json" }, dir => {
        const said = checkHarness.check(dir).failed.map(f => f.title).join("\n");
        t.ok(said.includes("readable JSON"), "hook launcher: a settings file that is not JSON fails rather than passing quietly", said);
    });
}

module.exports = [
    rootDecisions,
    hookLauncherDecisions,
    repoViewDecisions,
    stagedChainDecisions,
    skillRosterDecisions,
    projectFactDecisions,
    commitMessageDecisions,
    todoDecisions,
    sourceDecisions,
    chainMembership,
];
