// .agents/hooks/tests/tables.js
// Decision tables: a check's input and the verdict it must give, run in this process against a
// throwaway root. A command reads the repo it sits in, so a fixture piped to one can only ever see
// this checkout's MEMORY.md and tracker config, and a case about another project's settings had no
// way in. check(input, root) takes the repo as an argument, so each row names the files that repo
// holds and nothing here depends on the checkout the suite runs in.
// Registered like self-checks.js: test.js runs the exported array after it, and a function left out
// of the array is caught by everyCheckIsRegistered there. cases.tsv keeps one row per script, which
// proves the command line still reaches the decision.
const fs = require("fs");
const os = require("os");
const path = require("path");
const commitMsg = require("../../../scripts/check-commit-msg");
const todo = require("../../../scripts/check-todo");
const docsCheck = require("../../../scripts/docs-check");
const stagedDocs = require("../../../scripts/check-staged-docs");
const facts = require("../../../scripts/project-facts");

// A temp repo holding `files` (repo-relative path -> content), handed to `use`, and removed after.
function withRoot(files, use) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "harness-table-"));
    try {
        for (const [rel, text] of Object.entries(files)) {
            fs.mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true });
            fs.writeFileSync(path.join(dir, rel), text);
        }
        return use(dir);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

const text = (...lines) => lines.join("\n") + "\n";

// A message's verdict: blocked with a problem containing `blocks`, or accepted, warned about
// `warns` or about nothing when `warns` is null. `summary` is a substring of what an accepted
// message prints.
function commitMessageDecisions(t) {
    const WHY = "The git-commit skill writes them; this holds whatever wrote them to the\nsame rule, agent or human.";
    const TRACKER = "docs/agents/issue-tracker.md";
    const rows = [
        // files, message, blocks, warns, summary, why
        [{}, text("feat(hooks): check the shape of every commit message", "", WHY), null, "PROJ-123", "conventional",
            "a conventional subject with a body passes"],
        [{}, text("Route aspnet-core for the engineer"), "not a conventional commit", undefined, null,
            "a sentence-style subject is rejected"],
        [{}, text("chore: tidy the lock file."), "ends with a full stop", undefined, null,
            "a subject ending in a full stop is rejected"],
        [{}, text("Merge branch master into feature"), null, null, "generated by git",
            "a merge message git wrote itself is not checked"],
        [{}, text("feat(hooks): warn when a commit cites no issue key", "", "The key is encouragement, not a gate: a change can be real before anyone\nhas raised a ticket for it."),
            null, "no issue key", "conventional", "a message citing no issue warns but is not rejected"],
        [{}, text("fix(hooks): cite the ticket this change came from (AB-42)", "", "The key ties the commit back to the work item that asked for it."),
            null, null, "conventional", "a message citing an issue passes without the warning"],
        [{}, text("fix: fixing bugs", "", "A body long enough to pass the body rule on its own."), "the description is 2 word(s)", undefined, null,
            "a two-word description is rejected however long the body"],
        [{}, text("feat(hooks): reject a commit that carries no body at all"), "there is no description", undefined, null,
            "a subject with no body is rejected"],
        [{}, text("feat(hooks): reject a body that is only a trailer line", "", "Refs: AB-42"), "there is no description", undefined, null,
            "a body that is only a trailer does not count as a description"],
        [{}, text("feat(hooks): count an issue key only where it refers", "", 'A body that merely quotes "Refs: AB-42" as an example of a trailer is\nprose about a ticket, not a reference to one.'),
            null, "no issue key", "conventional", "a key quoted in the body is prose, not a reference, so the warning stands"],
        [{}, text("feat(hooks): accept an issue key from a trailer line", "", "The trailer is where Git convention puts a reference.", "", "Refs: AB-42"),
            null, null, "conventional", "a key in a trailer line counts, so no warning"],

        // What an issue reference looks like is the project's decision, read from its own tracker
        // config and MEMORY.md. Each of these is a valid message, so only the warning varies.
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "AB-123", "conventional", "the project's own key becomes the example in the warning"],
        [{ [TRACKER]: "**Project key:** `AB`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month.", "", "Refs: AB-42"),
            null, null, "conventional", "a key matching the project's own is a reference"],
        // GitHub Issues cite #42, which is nothing like AB-42, so a project says so with a regular
        // expression and is warned about the right thing.
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, "#\\d+", "conventional", "a configured key format replaces the example"],
        [{ [TRACKER]: "**Key format:** `#\\d+`\n" }, text("feat(billing): add a monthly invoice run (#42)", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a reference matching the configured format counts"],
        // A project that plans in docs/ has already answered the question, so asking again on every
        // commit is asking for something it said it does not have.
        [{ "MEMORY.md": "- **Issue tracker:** none\n" }, text("feat(billing): add a monthly invoice run", "", "Invoices were cut by hand every month."),
            null, null, "conventional", "a project recording no tracker is never warned"],
    ];
    for (const [files, message, blocks, warns, summary, why] of rows) {
        const r = withRoot(files, root => commitMsg.check(message, root));
        const detail = JSON.stringify(r);
        const verdict = blocks
            ? r.problems.some(p => p.includes(blocks))
            : !r.problems.length && r.summary.includes(summary)
                && (warns === null ? !r.warnings.length : r.warnings.length === 1 && r.warnings[0].includes(warns))
                && !(warns === "#\\d+" && r.warnings[0].includes("PROJ-123"));
        t.ok(verdict, `check-commit-msg: ${why}`, detail);
    }
}

// A ledger's verdict: blocked with a problem containing `blocks`, or accepted with a summary
// containing `summary`. Sources that look like paths resolve against the root each row is given.
function todoDecisions(t) {
    const REPO = { "AGENTS.md": "# Agents\n", "scripts/githooks-init.js": "// init\n", "src/billing.cs": "// there\n" };
    const rows = [
        // ledger, blocks, summary, why
        [text("# TODO", "", "What has nowhere else to live. The loose-ends skill has the format.", "",
            "- [ ] Does the initialisation gate belong on push as well? #question (AGENTS.md)",
            "- [ ] Every clone has run githooks-init #assumption @yaroslav (scripts/githooks-init.js:1)",
            "- [ ] No test covers the relink path #deferred (jira:AB-42)",
            "  - [ ] and the absolute-link case under it is untested too",
            "- [ ] Revisit once the spec settles #deferred (https://example.com/spec)"),
            null, "all well formed", "every tag, a subtask, an assignee and each kind of source all pass"],
        [text("- [ ] An entry with no file header #question (AGENTS.md)"), 'must open with "# TODO"', null,
            "todo-md requires the header, so a file of bare entries is rejected"],
        [text("# TODO", "", "- [ ] Something vague #todo (AGENTS.md)"), "unknown tag", null, "a tag outside the three kinds is rejected"],
        [text("# TODO", "", "- [x] This one was answered #question (AGENTS.md)"), 'a "[x]" entry', null, "a resolved entry is deleted, not ticked"],
        [text("# TODO", "", "- [-] We decided against this #deferred (AGENTS.md)"), 'a "[-]" entry', null,
            "a declined entry is deleted too, though todo-md would keep it"],
        [text("# TODO", "", "- [ ] Where should this live? #question"), "no source", null,
            "an entry that says nothing about where it came from is rejected"],
        [text("# TODO", "", "- [ ] Where should this live? #question (during the review)"), "is not a source", null,
            "prose in place of a source is rejected"],
        [text("# TODO", "", "Nothing outstanding right now."), null, "0 open item(s)", "a file with the header and no entries passes"],
        ["", null, "nothing to check", "an empty ledger is not a problem"],
        [text("# TODO", "", "- [ ] Confirm the rounding rule #question (src/billing.cs:12)"), null, "1 open item(s)",
            "a path:line source resolves in the root it was given"],
        // As a command, the root is always this checkout, so a fixture could only cite a file the
        // template happens to ship; this is the row that proves the resolution rather than assuming it.
        [text("# TODO", "", "- [ ] Confirm the rounding rule #question (scripts/lib.js)"), "is not a source", null,
            "a path outside that root is not a source, however real it is here"],
        [text("# TODO", "", "- [ ] Split the billing folder #deferred (src)"), "is not a source", null,
            "a bare folder name is prose, as it is in a Derived from line"],
        [text("# TODO", "", "- [ ] Split the billing folder #deferred (src/)"), null, "1 open item(s)",
            "a folder written with its slash is a source"],
        [text("# TODO", "", "- [ ] Chase the ticket #deferred (jira:ab-42)"), "is not a source", null,
            "a lower-case Jira key is rejected, as docs-check rejects it"],
    ];
    for (const [ledger, blocks, summary, why] of rows) {
        const r = withRoot(REPO, root => todo.check(ledger, root));
        const verdict = blocks ? r.problems.some(p => p.includes(blocks)) : !r.problems.length && r.summary.includes(summary);
        t.ok(verdict, `check-todo: ${why}`, r.problems.join("\n") || r.summary);
    }
}

// What counts as a source, the one rule "Derived from:", MEMORY.md's Requirements and TODO.md share.
function sourceDecisions(t) {
    const REPO = { "INTENT.md": "# INTENT.md\n", "src/billing.cs": "// there\n", "docs/brief.md": "# Brief\n" };
    const rows = [
        // token, is a source, why
        ["https://example.com/spec", true, "a URL"],
        ["jira:AB-42", true, "an upper-case Jira key"],
        ["jira:MY_PROJ-7", true, "a Jira key with an underscore, which Jira allows"],
        ["jira:ab-42", false, "a lower-case Jira key, which Jira never issues"],
        ["src/billing.cs", true, "a path that exists"],
        ["src/billing.cs:12", true, "path:line, where the file exists"],
        ["src/billing.cs:12-40", true, "path:from-to, where the file exists"],
        ["src/missing.cs:12", false, "path:line whose file does not exist"],
        ["src/", true, "a folder, written with its slash"],
        ["src", false, "a bare word, even one naming a real folder"],
        ["INTENT.md", true, "a file at the root"],
        ["Node.js", false, "prose with a dot"],
        ["during the review", false, "prose"],
    ];
    withRoot(REPO, root => {
        for (const [token, want, why] of rows) {
            t.ok(docsCheck.isSource(token, root) === want, `isSource: ${why}`, `${token} -> ${!want}`);
        }
    });
}

// Which files are the chain. The edit hook and the pre-commit hook both ask inChain, so one table
// pins what an edit and a commit check.
function chainMembership(t) {
    const rows = [
        ["docs/brd/0001-x.md", true, "a document under docs/"],
        ["docs/README.md", true, "any Markdown under docs/"],
        ["AGENTS.md", true, "the table that defines the stages"],
        ["MEMORY.md", true, "MEMORY.md, whose Requirements line enters the chain"],
        ["INTENT.md", true, "INTENT.md"],
        ["docs/diagram.png", false, "a file under docs/ that is not Markdown"],
        ["README.md", false, "Markdown outside docs/"],
        ["src/docs/x.md", false, "a docs/ folder that is not at the root"],
    ];
    for (const [file, want, why] of rows) {
        t.ok(docsCheck.inChain(file) === want, `inChain: ${why}`, `${file} -> ${!want}`);
    }
    const staged = rows.map(r => r[0]);
    t.ok(JSON.stringify(stagedDocs.chainFiles(staged)) === JSON.stringify(staged.filter(docsCheck.inChain)),
        "the pre-commit hook's staged filter is inChain", stagedDocs.chainFiles(staged).join(" "));
}

// What every reader of project facts sees, from the texts of MEMORY.md and INTENT.md (null: no such
// file). A label reads null when nothing gives it, "" when it is unanswered, and its value otherwise.
function projectFactDecisions(t) {
    const INTENT = text("# INTENT.md", "", "## Product", "", "**Acme Billing** invoices small firms monthly.", "", "## MVP stories", "");
    const rows = [
        // memory, intent, label, expected, why
        [text("- **Language:** C#"), null, "Language", "C#", "a dash bullet with the colon inside the bold"],
        [text("* **Language**: C#"), null, "Language", "C#", "a star bullet with the colon after the bold"],
        [text("-**Language:** C#"), null, "Language", "C#", "no space after the bullet"],
        [text("- **language:** C#"), null, "Language", "C#", "the label in another case"],
        [text("- **Language:**   C#  "), null, "Language", "C#", "the value is trimmed"],
        ["- **Language:** C#\r\n- **Unit type:** service\r\n", null, "Unit type", "service", "CRLF line endings"],
        [text("Language: C#"), null, "Language", null, "an unbolded line is prose, not a fact"],
        [text("- Language: C#"), null, "Language", null, "an unbolded bullet is prose too"],
        [text("**Language:** C#"), null, "Language", null, "a bold label with no bullet is not a fact line"],
        [text("- **Languages:** C#"), null, "Language", null, "a longer label is another fact"],
        [text("- **Runtime / package manager:** Node 22 / pnpm"), null, "Runtime / package manager", "Node 22 / pnpm",
            "a label holding a slash"],
        [null, null, "Language", null, "no MEMORY.md at all"],
        [text("- **Language:**"), null, "Language", "", "an empty value is unanswered"],
        [text("- **Language:** <language>"), null, "Language", "", "a placeholder is unanswered"],
        [text("- **Language:** <language> <version>"), null, "Language", "", "several placeholders and nothing else are unanswered"],
        [text("- **Issue tracker:** <tracker> at <url>"), null, "Issue tracker", "<tracker> at <url>",
            "words beside placeholders make an answer, kept whole"],
        [text("- **Issue tracker:** none"), null, "Issue tracker", "none", "an optional fact reads like any other"],
        // INTENT.md owns the name and purpose outright; the configuration stays MEMORY.md's.
        [text("- **Name:** Old Name"), INTENT, "Name", "Acme Billing", "INTENT.md's bold name wins over MEMORY.md"],
        [text("- **Purpose:** old"), INTENT, "Purpose", "invoices small firms monthly.", "the purpose is INTENT.md's prose"],
        [text("- **Name:** Old Name"), INTENT.replace("**Acme Billing** ", ""), "Name", "",
            "an INTENT.md naming no product leaves Name unanswered, with no fallback"],
        [text("- **Name:** Old Name"), text("# INTENT.md", "", "## MVP stories"), "Name", null,
            "an INTENT.md with no Product gives no name, with no fallback"],
        [null, text("# INTENT.md", "", "## Product", "", "**<name>** <purpose>"), "Name", "", "a template INTENT.md is unanswered"],
        [text("- **Language:** C#"), INTENT, "Language", "C#", "INTENT.md does not stand in for configuration"],
        [text("- **Name:** Acme"), null, "Name", "Acme", "without INTENT.md the name is MEMORY.md's"],
    ];
    for (const [memory, intent, label, want, why] of rows) {
        const got = facts.readFacts({ memory, intent })[label];
        t.ok(got === want, `project facts: ${why}`, `${label} -> ${JSON.stringify(got)}, wanted ${JSON.stringify(want)}`);
    }

    const all = text(...facts.FACTS.map(f => `- **${f.label}:** x`));
    t.ok(facts.unanswered(facts.readFacts({ memory: all })).length === 0, "project facts: nothing unanswered when every line has a value");
    t.ok(facts.unanswered(facts.readFacts({ memory: text("- **Issue tracker:** Jira") })).join() === facts.FACTS.filter(f => f.required).map(f => f.label).join(),
        "project facts: unanswered lists the required facts only, in order", facts.unanswered(facts.readFacts({})).join());

    const parsed = facts.readIntent(INTENT);
    t.ok(parsed.title && parsed.stories && parsed.product.name === "Acme Billing" && parsed.product.purpose === "invoices small firms monthly.",
        "project facts: readIntent separates the bold name from the purpose", JSON.stringify(parsed));

    // readFactsAt reads the files a root holds, or the paths it is given instead.
    withRoot({ "MEMORY.md": text("- **Language:** C#"), "staged/memory.md": text("- **Language:** F#") }, root => {
        t.ok(facts.readFactsAt(root).Language === "C#", "project facts: readFactsAt reads MEMORY.md at the root");
        t.ok(facts.readFactsAt(root, path.join(root, "staged/memory.md")).Language === "F#",
            "project facts: readFactsAt reads another path when given one");
    });
}

module.exports = [
    projectFactDecisions,
    commitMessageDecisions,
    todoDecisions,
    sourceDecisions,
    chainMembership,
];
